use super::Context;
use anyhow::Result;
use bs_git::Miner;
use clap::Args;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Args)]
pub struct MemoArgs {
    /// Regenerate worklog from git history and write to .borescope/worklog.toml
    #[arg(long)]
    pub update: bool,

    /// Show recent authors for a file or symbol area (path prefix match)
    #[arg(long)]
    pub who: Option<String>,

    /// Days of history to include in worklog (used with --update)
    #[arg(long, default_value = "90")]
    pub days: u32,
}

// ── memo.toml (team-committed, human-curated) ────────────────────────────────

#[derive(Debug, Default, Deserialize)]
struct Memo {
    #[serde(default)]
    project: ProjectSection,
    #[serde(default)]
    decisions: Vec<Decision>,
    #[serde(default)]
    notes: Vec<Note>,
}

#[derive(Debug, Default, Deserialize)]
struct ProjectSection {
    #[serde(default)]
    name: String,
    #[serde(default)]
    description: String,
    #[serde(default)]
    entry_points: Vec<String>,
    #[serde(default)]
    danger_zones: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct Decision {
    title: String,
    #[serde(default)]
    when: String,
    #[serde(default)]
    rationale: String,
}

#[derive(Debug, Deserialize)]
struct Note {
    text: String,
    #[serde(default)]
    author: String,
    #[serde(default)]
    date: String,
}

// ── worklog.toml (auto-generated, gitignored) ────────────────────────────────

#[derive(Debug, Default, Serialize, Deserialize)]
struct Worklog {
    generated: String,
    days: u32,
    entries: Vec<WorklogRecord>,
}

#[derive(Debug, Serialize, Deserialize)]
struct WorklogRecord {
    author: String,
    date: String,
    subject: String,
    files: Vec<String>,
}

// ── command entry point ───────────────────────────────────────────────────────

pub fn run(ctx: &Context, args: &MemoArgs) -> Result<()> {
    let borescope_dir = ctx.repo_root.join(".borescope");
    let memo_path = borescope_dir.join("memo.toml");
    let worklog_path = borescope_dir.join("worklog.toml");

    if args.update {
        cmd_update(ctx, &worklog_path, args.days)?;
        return Ok(());
    }

    if let Some(ref target) = args.who {
        cmd_who(ctx, &worklog_path, target)?;
        return Ok(());
    }

    cmd_show(ctx, &memo_path, &worklog_path)
}

// ── --update: mine git, write worklog.toml ───────────────────────────────────

fn cmd_update(ctx: &Context, worklog_path: &PathBuf, days: u32) -> Result<()> {
    let miner = Miner::new(ctx.repo_root.clone());
    let entries = miner.worklog(days)?;

    let records: Vec<WorklogRecord> = entries
        .into_iter()
        .map(|e| WorklogRecord {
            author: e.author,
            date: e.date,
            subject: e.subject,
            files: e.files,
        })
        .collect();

    let now = chrono_date();
    let wl = Worklog {
        generated: now,
        days,
        entries: records,
    };

    let toml_str = toml::to_string_pretty(&wl)?;
    let header = format!(
        "# Auto-generated by `borescope memo --update`. Do not edit — commit memo.toml instead.\n\n{}",
        toml_str
    );
    std::fs::write(worklog_path, &header)?;

    if !ctx.quiet {
        eprintln!(
            "worklog updated: {} entries written to {}",
            wl.entries.len(),
            worklog_path.display()
        );
        eprintln!(
            "hint: add .borescope/worklog.toml to .gitignore; commit .borescope/memo.toml"
        );
    }
    Ok(())
}

// ── --who <target>: show recent authors for a file/area ──────────────────────

fn cmd_who(_ctx: &Context, worklog_path: &PathBuf, target: &str) -> Result<()> {
    let wl = load_worklog(worklog_path);

    // Strip symbol suffix if present (path:Symbol → path)
    let path_prefix = if let Some(colon) = target.rfind(':') {
        let before = &target[..colon];
        if before.contains('/') || before.contains('.') {
            before
        } else {
            target
        }
    } else {
        target
    };

    let matches: Vec<&WorklogRecord> = wl
        .entries
        .iter()
        .filter(|e| e.files.iter().any(|f| f.contains(path_prefix)))
        .collect();

    if matches.is_empty() {
        println!("no recent activity found for: {}", target);
        return Ok(());
    }

    println!("recent activity in {} (last {} days):", path_prefix, wl.days);
    println!();
    for e in &matches {
        let file_preview = if e.files.len() == 1 {
            e.files[0].clone()
        } else {
            format!("{} (+{} more)", e.files[0], e.files.len() - 1)
        };
        println!("  {:<20} {}  {}", e.author, e.date, e.subject);
        println!("  {:<20} {}", "", file_preview);
        println!();
    }
    Ok(())
}

// ── default: show memo + recent worklog ──────────────────────────────────────

fn cmd_show(ctx: &Context, memo_path: &PathBuf, worklog_path: &PathBuf) -> Result<()> {
    let memo = load_memo(memo_path);
    let wl = load_worklog(worklog_path);

    // Project section
    if !memo.project.name.is_empty() || !memo.project.description.is_empty() {
        let name = if memo.project.name.is_empty() {
            ctx.repo_root
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("(unnamed)")
                .to_string()
        } else {
            memo.project.name.clone()
        };
        println!("project: {}", name);
        if !memo.project.description.is_empty() {
            for line in memo.project.description.lines() {
                println!("  {}", line);
            }
        }
        println!();
    } else if !memo_path.exists() {
        println!("(no memo.toml found — run `borescope memo --update` to generate the worklog,");
        println!(" then create .borescope/memo.toml to add project context)");
        println!();
    }

    if !memo.project.entry_points.is_empty() {
        println!("entry points:");
        for ep in &memo.project.entry_points {
            println!("  {}", ep);
        }
        println!();
    }

    if !memo.project.danger_zones.is_empty() {
        println!("danger zones:");
        for dz in &memo.project.danger_zones {
            println!("  ⚠  {}", dz);
        }
        println!();
    }

    if !memo.decisions.is_empty() {
        println!("architectural decisions ({}):", memo.decisions.len());
        for d in &memo.decisions {
            let when = if d.when.is_empty() {
                String::new()
            } else {
                format!("[{}] ", d.when)
            };
            println!("  {}{}", when, d.title);
            if !d.rationale.is_empty() {
                println!("    {}", d.rationale);
            }
        }
        println!();
    }

    if !memo.notes.is_empty() {
        println!("team notes:");
        for n in &memo.notes {
            let by = if n.author.is_empty() {
                String::new()
            } else {
                format!(" — {}", n.author)
            };
            let when = if n.date.is_empty() {
                String::new()
            } else {
                format!(" ({})", n.date)
            };
            println!("  {}{}{}", n.text, by, when);
        }
        println!();
    }

    // Worklog section
    if wl.entries.is_empty() {
        if !wl.generated.is_empty() {
            println!("recent work: (none in last {} days)", wl.days);
        } else {
            println!("recent work: run `borescope memo --update` to generate from git history");
        }
    } else {
        println!(
            "recent work (last {} days, {} commits):",
            wl.days,
            wl.entries.len()
        );
        println!();
        for e in wl.entries.iter().take(20) {
            let file_summary = if e.files.is_empty() {
                String::new()
            } else if e.files.len() == 1 {
                format!("    {}", e.files[0])
            } else {
                format!("    {} (+{} more)", e.files[0], e.files.len() - 1)
            };
            println!("  {:<20} {}  {}", e.author, e.date, e.subject);
            if !file_summary.is_empty() {
                println!("{}", file_summary);
            }
        }
        if wl.entries.len() > 20 {
            println!("  ... ({} more — use --who <path> to filter)", wl.entries.len() - 20);
        }
        if !wl.generated.is_empty() {
            println!();
            println!("  worklog generated: {}  (re-run `borescope memo --update` to refresh)", wl.generated);
        }
    }

    Ok(())
}

// ── helpers ──────────────────────────────────────────────────────────────────

fn load_memo(path: &PathBuf) -> Memo {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| toml::from_str(&s).ok())
        .unwrap_or_default()
}

fn load_worklog(path: &PathBuf) -> Worklog {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| toml::from_str(&s).ok())
        .unwrap_or_default()
}

fn chrono_date() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let days_since_epoch = secs / 86400;
    // Rough Gregorian calendar — good enough for display
    let mut y = 1970u32;
    let mut d = days_since_epoch as u32;
    loop {
        let days_in_year = if y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) { 366 } else { 365 };
        if d < days_in_year { break; }
        d -= days_in_year;
        y += 1;
    }
    let month_days = [31u32, 28 + if y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) { 1 } else { 0 }, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    let mut m = 0usize;
    while m < 11 && d >= month_days[m] { d -= month_days[m]; m += 1; }
    format!("{:04}-{:02}-{:02}", y, m + 1, d + 1)
}

